### ISSUE TITLE
怎么才能加入绿帽子安全社区呢？

### ISSUE THREAD

**Issue by cainiao01-ss** [GREENHAT7/2022#1]
怎么才能加入绿帽子安全社区呢？

**Comment by tangxiaofeng7** [comment]
> 怎么才能加入绿帽子安全社区呢？

论坛采取邀请制：找一个已注册的会员邀请即可

**Comment by insmite** [comment]
邀请一下吧

**Comment by cainiao01-ss** [comment]
> > 怎么能加入绿帽子安全社区呢？
> 
> 论坛发起邀请制 一个已注册的会员邀请：寻找

我找不到认识的已注册的会员，能发送一个邀请码吗？
